@startuml
skinparam defaultFontName Arial
skinparam shadowing false
skinparam packageStyle rectangle
left to right direction
actor "Thủ thư" as T
rectangle "Mượn trả sách" {
  usecase "UC10 Lập phiếu mượn" as UC10
  usecase "UC11 In phiếu mượn" as UC11
  usecase "UC12 Trả sách" as UC12
  usecase "UC13 Gia hạn phiếu mượn" as UC13
}
T -- UC10
T -- UC11
T -- UC12
T -- UC13
UC11 .> UC10 : <<extend>>
@enduml
