@startuml
skinparam defaultFontName Arial
skinparam shadowing false
skinparam packageStyle rectangle
left to right direction
actor "Thủ thư" as T
actor "Quản trị viên" as A
T <|-- A
rectangle "Quản lý độc giả" {
  usecase "UC06 Thêm độc giả" as UC06
  usecase "UC07 Sửa độc giả" as UC07
  usecase "UC08 Tìm kiếm độc giả" as UC08
  usecase "UC09 Lưu trữ độc giả" as UC09
}
T -- UC06
T -- UC07
T -- UC08
A -- UC09
UC07 ..> UC08 : <<include>>
UC09 ..> UC08 : <<include>>
@enduml
