@startchen
skinparam defaultFontName Arial
skinparam shadowing false

entity "NGƯỜI DÙNG" as ND {
  MaNguoiDung <<key>>
  TenDangNhap
  MatKhau
  HoTen
  Email
  DienThoai
  VaiTro
  TrangThai
}
entity "ĐỘC GIẢ" as DG {
  MaDocGia <<key>>
  HoTen
  DienThoai
  TrangThai
}
entity "SÁCH" as S {
  MaSach <<key>>
  MaISBN
  TenSach
  TacGia
  TheLoai
  TongSoBan
  TrangThai
  SoBanCoSan <<derived>>
}
entity "PHIẾU MƯỢN" as PM {
  SoPhieu <<key>>
  NgayMuon
  HanTra
  DaGiaHan
}
entity "CHI TIẾT PHIẾU MƯỢN" as CT <<weak>> {
  NgayTra
}
relationship "MƯỢN" as MUON {
}
relationship "LẬP" as LAP {
}
relationship "CÓ" as CO <<identifying>> {
}
relationship "LÀ BẢN CỦA" as THUOC {
}
relationship "NHẬN TRẢ" as NHANTRA {
}
DG -1- MUON
MUON =N= PM
ND -1- LAP
LAP =N= PM
PM =1= CO
CO =N= CT
CT =N= THUOC
THUOC -1- S
ND -1- NHANTRA
NHANTRA -N- CT
@endchen
